/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Category = IDL.Record({
  'id' : IDL.Text,
  'nameDe' : IDL.Text,
  'nameEn' : IDL.Text,
  'createdAt' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FeedbackResponse = IDL.Record({
  'id' : IDL.Text,
  'admin' : IDL.Principal,
  'videoResponse' : IDL.Opt(ExternalBlob),
  'createdAt' : Time,
  'submissionId' : IDL.Text,
  'textResponse' : IDL.Opt(IDL.Text),
});
export const FileReference = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadedAt' : Time,
});
export const LearningPath = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'lessonIds' : IDL.Vec(IDL.Text),
});
export const MembershipTier = IDL.Variant({
  'pro' : IDL.Null,
  'coaching' : IDL.Null,
  'starter' : IDL.Null,
  'free' : IDL.Null,
  'visitor' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'title' : IDL.Text,
  'pdfFile' : IDL.Opt(ExternalBlob),
  'thumbnail' : IDL.Opt(ExternalBlob),
  'levelId' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'recommendedNextLessonId' : IDL.Opt(IDL.Text),
  'requiredMembership' : MembershipTier,
  'videoUrl' : IDL.Text,
  'gpFile' : IDL.Opt(ExternalBlob),
});
export const Level = IDL.Record({
  'id' : IDL.Text,
  'nameDe' : IDL.Text,
  'nameEn' : IDL.Text,
  'createdAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
  'streaming_strategy' : IDL.Opt(
    IDL.Variant({ 'Callback' : IDL.Record({ 'token' : IDL.Vec(IDL.Nat8) }) })
  ),
  'status_code' : IDL.Nat16,
});
export const Progress = IDL.Record({
  'lessonId' : IDL.Text,
  'lastAccessed' : Time,
  'completed' : IDL.Bool,
});
export const FeatureCard = IDL.Record({
  'id' : IDL.Text,
  'descriptionDe' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'icon' : IDL.Opt(ExternalBlob),
  'titleDe' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const WhyChooseSection = IDL.Record({
  'descriptionDe' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'featureCards' : IDL.Vec(FeatureCard),
  'titleDe' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const PricingOption = IDL.Record({
  'id' : IDL.Text,
  'nameDe' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionDe' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'priceEur' : IDL.Nat,
  'membershipTier' : MembershipTier,
});
export const TierFeature = IDL.Record({
  'id' : IDL.Text,
  'featureDe' : IDL.Text,
  'featureEn' : IDL.Text,
  'position' : IDL.Nat,
});
export const TierFeatureList = IDL.Record({
  'features' : IDL.Vec(TierFeature),
  'tier' : MembershipTier,
});
export const ChooseYourPathSection = IDL.Record({
  'descriptionDe' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'pricingOptions' : IDL.Vec(PricingOption),
  'tierFeatures' : IDL.Vec(TierFeatureList),
  'titleDe' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const HomepageContent = IDL.Record({
  'lastUpdated' : Time,
  'heroImage' : IDL.Opt(ExternalBlob),
  'headerLogo' : IDL.Opt(ExternalBlob),
  'whyChooseSection' : WhyChooseSection,
  'chooseYourPathSection' : ChooseYourPathSection,
  'heroTextDe' : IDL.Text,
  'heroTextEn' : IDL.Text,
});
export const FeedbackStatus = IDL.Variant({
  'responded' : IDL.Null,
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const FeedbackSubmission = IDL.Record({
  'id' : IDL.Text,
  'lessonId' : IDL.Text,
  'status' : FeedbackStatus,
  'youtubeLink' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'submittedAt' : Time,
  'videoFile' : IDL.Opt(ExternalBlob),
  'comment' : IDL.Text,
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'light' : IDL.Null,
});
export const LanguagePreference = IDL.Variant({
  'german' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'theme' : ThemePreference,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'language' : LanguagePreference,
  'isSuspended' : IDL.Bool,
  'membership' : MembershipTier,
});
export const ExportData = IDL.Record({
  'files' : IDL.Vec(FileReference),
  'categories' : IDL.Vec(Category),
  'userProgress' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Progress))),
  'homepageContent' : IDL.Opt(HomepageContent),
  'feedbackResponses' : IDL.Vec(FeedbackResponse),
  'feedbackSubmissions' : IDL.Vec(FeedbackSubmission),
  'learningPaths' : IDL.Vec(LearningPath),
  'lessons' : IDL.Vec(Lesson),
  'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'levels' : IDL.Vec(Level),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addFeedbackResponse' : IDL.Func([FeedbackResponse], [], []),
  'addFileReference' : IDL.Func([FileReference], [], []),
  'addLearningPath' : IDL.Func([LearningPath], [], []),
  'addLesson' : IDL.Func([Lesson], [], []),
  'addLevel' : IDL.Func([Level], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteLearningPath' : IDL.Func([IDL.Text], [], []),
  'deleteLesson' : IDL.Func([IDL.Text], [], []),
  'deleteLevel' : IDL.Func([IDL.Text], [], []),
  'downloadPdfFile' : IDL.Func([IDL.Text], [HttpResponse], ['query']),
  'exportData' : IDL.Func([], [ExportData], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerFeedbackSubmissions' : IDL.Func(
      [],
      [IDL.Vec(FeedbackSubmission)],
      ['query'],
    ),
  'getCallerLanguagePreference' : IDL.Func([], [LanguagePreference], ['query']),
  'getCallerProgress' : IDL.Func([], [IDL.Opt(IDL.Vec(Progress))], ['query']),
  'getCallerThemePreference' : IDL.Func([], [ThemePreference], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFeedbackResponses' : IDL.Func([], [IDL.Vec(FeedbackResponse)], ['query']),
  'getFeedbackResponsesForSubmission' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeedbackResponse)],
      ['query'],
    ),
  'getFeedbackSubmissions' : IDL.Func(
      [],
      [IDL.Vec(FeedbackSubmission)],
      ['query'],
    ),
  'getFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'getHomepageContent' : IDL.Func([], [IDL.Opt(HomepageContent)], ['query']),
  'getLearningPaths' : IDL.Func([], [IDL.Vec(LearningPath)], ['query']),
  'getLessonById' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
  'getLessonCompletionStatus' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getLessonsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getLessonsByLevel' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getLessonsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getLevels' : IDL.Func([], [IDL.Vec(Level)], ['query']),
  'getRecommendedLessons' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Vec(Lesson)],
      ['query'],
    ),
  'getStripeConfiguration' : IDL.Func(
      [],
      [IDL.Opt(StripeConfiguration)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importData' : IDL.Func([ExportData], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'reactivateUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'servePdfFile' : IDL.Func([IDL.Text], [HttpResponse], ['query']),
  'setCallerLanguagePreference' : IDL.Func([LanguagePreference], [], []),
  'setCallerThemePreference' : IDL.Func([ThemePreference], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitFeedback' : IDL.Func([FeedbackSubmission], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerProgress' : IDL.Func([IDL.Vec(Progress)], [], []),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
  'updateLearningPath' : IDL.Func([LearningPath], [], []),
  'updateLesson' : IDL.Func([Lesson], [], []),
  'updateLevel' : IDL.Func([Level], [], []),
  'updateTierFeatures' : IDL.Func([IDL.Vec(TierFeatureList)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Category = IDL.Record({
    'id' : IDL.Text,
    'nameDe' : IDL.Text,
    'nameEn' : IDL.Text,
    'createdAt' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FeedbackResponse = IDL.Record({
    'id' : IDL.Text,
    'admin' : IDL.Principal,
    'videoResponse' : IDL.Opt(ExternalBlob),
    'createdAt' : Time,
    'submissionId' : IDL.Text,
    'textResponse' : IDL.Opt(IDL.Text),
  });
  const FileReference = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadedAt' : Time,
  });
  const LearningPath = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'lessonIds' : IDL.Vec(IDL.Text),
  });
  const MembershipTier = IDL.Variant({
    'pro' : IDL.Null,
    'coaching' : IDL.Null,
    'starter' : IDL.Null,
    'free' : IDL.Null,
    'visitor' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'title' : IDL.Text,
    'pdfFile' : IDL.Opt(ExternalBlob),
    'thumbnail' : IDL.Opt(ExternalBlob),
    'levelId' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'recommendedNextLessonId' : IDL.Opt(IDL.Text),
    'requiredMembership' : MembershipTier,
    'videoUrl' : IDL.Text,
    'gpFile' : IDL.Opt(ExternalBlob),
  });
  const Level = IDL.Record({
    'id' : IDL.Text,
    'nameDe' : IDL.Text,
    'nameEn' : IDL.Text,
    'createdAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
    'streaming_strategy' : IDL.Opt(
      IDL.Variant({ 'Callback' : IDL.Record({ 'token' : IDL.Vec(IDL.Nat8) }) })
    ),
    'status_code' : IDL.Nat16,
  });
  const Progress = IDL.Record({
    'lessonId' : IDL.Text,
    'lastAccessed' : Time,
    'completed' : IDL.Bool,
  });
  const FeatureCard = IDL.Record({
    'id' : IDL.Text,
    'descriptionDe' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'icon' : IDL.Opt(ExternalBlob),
    'titleDe' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const WhyChooseSection = IDL.Record({
    'descriptionDe' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'featureCards' : IDL.Vec(FeatureCard),
    'titleDe' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const PricingOption = IDL.Record({
    'id' : IDL.Text,
    'nameDe' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionDe' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'priceEur' : IDL.Nat,
    'membershipTier' : MembershipTier,
  });
  const TierFeature = IDL.Record({
    'id' : IDL.Text,
    'featureDe' : IDL.Text,
    'featureEn' : IDL.Text,
    'position' : IDL.Nat,
  });
  const TierFeatureList = IDL.Record({
    'features' : IDL.Vec(TierFeature),
    'tier' : MembershipTier,
  });
  const ChooseYourPathSection = IDL.Record({
    'descriptionDe' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'pricingOptions' : IDL.Vec(PricingOption),
    'tierFeatures' : IDL.Vec(TierFeatureList),
    'titleDe' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const HomepageContent = IDL.Record({
    'lastUpdated' : Time,
    'heroImage' : IDL.Opt(ExternalBlob),
    'headerLogo' : IDL.Opt(ExternalBlob),
    'whyChooseSection' : WhyChooseSection,
    'chooseYourPathSection' : ChooseYourPathSection,
    'heroTextDe' : IDL.Text,
    'heroTextEn' : IDL.Text,
  });
  const FeedbackStatus = IDL.Variant({
    'responded' : IDL.Null,
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const FeedbackSubmission = IDL.Record({
    'id' : IDL.Text,
    'lessonId' : IDL.Text,
    'status' : FeedbackStatus,
    'youtubeLink' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'submittedAt' : Time,
    'videoFile' : IDL.Opt(ExternalBlob),
    'comment' : IDL.Text,
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'light' : IDL.Null,
  });
  const LanguagePreference = IDL.Variant({
    'german' : IDL.Null,
    'english' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'theme' : ThemePreference,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'language' : LanguagePreference,
    'isSuspended' : IDL.Bool,
    'membership' : MembershipTier,
  });
  const ExportData = IDL.Record({
    'files' : IDL.Vec(FileReference),
    'categories' : IDL.Vec(Category),
    'userProgress' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Progress))),
    'homepageContent' : IDL.Opt(HomepageContent),
    'feedbackResponses' : IDL.Vec(FeedbackResponse),
    'feedbackSubmissions' : IDL.Vec(FeedbackSubmission),
    'learningPaths' : IDL.Vec(LearningPath),
    'lessons' : IDL.Vec(Lesson),
    'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'levels' : IDL.Vec(Level),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addFeedbackResponse' : IDL.Func([FeedbackResponse], [], []),
    'addFileReference' : IDL.Func([FileReference], [], []),
    'addLearningPath' : IDL.Func([LearningPath], [], []),
    'addLesson' : IDL.Func([Lesson], [], []),
    'addLevel' : IDL.Func([Level], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteLearningPath' : IDL.Func([IDL.Text], [], []),
    'deleteLesson' : IDL.Func([IDL.Text], [], []),
    'deleteLevel' : IDL.Func([IDL.Text], [], []),
    'downloadPdfFile' : IDL.Func([IDL.Text], [HttpResponse], ['query']),
    'exportData' : IDL.Func([], [ExportData], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerFeedbackSubmissions' : IDL.Func(
        [],
        [IDL.Vec(FeedbackSubmission)],
        ['query'],
      ),
    'getCallerLanguagePreference' : IDL.Func(
        [],
        [LanguagePreference],
        ['query'],
      ),
    'getCallerProgress' : IDL.Func([], [IDL.Opt(IDL.Vec(Progress))], ['query']),
    'getCallerThemePreference' : IDL.Func([], [ThemePreference], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFeedbackResponses' : IDL.Func(
        [],
        [IDL.Vec(FeedbackResponse)],
        ['query'],
      ),
    'getFeedbackResponsesForSubmission' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedbackResponse)],
        ['query'],
      ),
    'getFeedbackSubmissions' : IDL.Func(
        [],
        [IDL.Vec(FeedbackSubmission)],
        ['query'],
      ),
    'getFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'getHomepageContent' : IDL.Func([], [IDL.Opt(HomepageContent)], ['query']),
    'getLearningPaths' : IDL.Func([], [IDL.Vec(LearningPath)], ['query']),
    'getLessonById' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
    'getLessonCompletionStatus' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getLessonsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getLessonsByLevel' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getLessonsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getLevels' : IDL.Func([], [IDL.Vec(Level)], ['query']),
    'getRecommendedLessons' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Vec(Lesson)],
        ['query'],
      ),
    'getStripeConfiguration' : IDL.Func(
        [],
        [IDL.Opt(StripeConfiguration)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importData' : IDL.Func([ExportData], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'reactivateUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'servePdfFile' : IDL.Func([IDL.Text], [HttpResponse], ['query']),
    'setCallerLanguagePreference' : IDL.Func([LanguagePreference], [], []),
    'setCallerThemePreference' : IDL.Func([ThemePreference], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitFeedback' : IDL.Func([FeedbackSubmission], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerProgress' : IDL.Func([IDL.Vec(Progress)], [], []),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
    'updateLearningPath' : IDL.Func([LearningPath], [], []),
    'updateLesson' : IDL.Func([Lesson], [], []),
    'updateLevel' : IDL.Func([Level], [], []),
    'updateTierFeatures' : IDL.Func([IDL.Vec(TierFeatureList)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };