/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'nameDe' : string,
  'nameEn' : string,
  'createdAt' : Time,
}
export interface ChooseYourPathSection {
  'descriptionDe' : string,
  'descriptionEn' : string,
  'pricingOptions' : Array<PricingOption>,
  'tierFeatures' : Array<TierFeatureList>,
  'titleDe' : string,
  'titleEn' : string,
}
export interface ExportData {
  'files' : Array<FileReference>,
  'categories' : Array<Category>,
  'userProgress' : Array<[Principal, Array<Progress>]>,
  'homepageContent' : [] | [HomepageContent],
  'feedbackResponses' : Array<FeedbackResponse>,
  'feedbackSubmissions' : Array<FeedbackSubmission>,
  'learningPaths' : Array<LearningPath>,
  'lessons' : Array<Lesson>,
  'userProfiles' : Array<[Principal, UserProfile]>,
  'levels' : Array<Level>,
}
export type ExternalBlob = Uint8Array;
export interface FeatureCard {
  'id' : string,
  'descriptionDe' : string,
  'descriptionEn' : string,
  'icon' : [] | [ExternalBlob],
  'titleDe' : string,
  'titleEn' : string,
}
export interface FeedbackResponse {
  'id' : string,
  'admin' : Principal,
  'videoResponse' : [] | [ExternalBlob],
  'createdAt' : Time,
  'submissionId' : string,
  'textResponse' : [] | [string],
}
export type FeedbackStatus = { 'responded' : null } |
  { 'pending' : null } |
  { 'reviewed' : null };
export interface FeedbackSubmission {
  'id' : string,
  'lessonId' : string,
  'status' : FeedbackStatus,
  'youtubeLink' : [] | [string],
  'user' : Principal,
  'submittedAt' : Time,
  'videoFile' : [] | [ExternalBlob],
  'comment' : string,
}
export interface FileReference {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploadedAt' : Time,
}
export interface HomepageContent {
  'lastUpdated' : Time,
  'heroImage' : [] | [ExternalBlob],
  'headerLogo' : [] | [ExternalBlob],
  'whyChooseSection' : WhyChooseSection,
  'chooseYourPathSection' : ChooseYourPathSection,
  'heroTextDe' : string,
  'heroTextEn' : string,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<{ 'value' : string, 'name' : string }>,
  'streaming_strategy' : [] | [{ 'Callback' : { 'token' : Uint8Array } }],
  'status_code' : number,
}
export type LanguagePreference = { 'german' : null } |
  { 'english' : null };
export interface LearningPath {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'lessonIds' : Array<string>,
}
export interface Lesson {
  'id' : string,
  'categoryId' : string,
  'title' : string,
  'pdfFile' : [] | [ExternalBlob],
  'thumbnail' : [] | [ExternalBlob],
  'levelId' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'recommendedNextLessonId' : [] | [string],
  'requiredMembership' : MembershipTier,
  'videoUrl' : string,
  'gpFile' : [] | [ExternalBlob],
}
export interface Level {
  'id' : string,
  'nameDe' : string,
  'nameEn' : string,
  'createdAt' : Time,
}
export type MembershipTier = { 'pro' : null } |
  { 'coaching' : null } |
  { 'starter' : null } |
  { 'free' : null } |
  { 'visitor' : null };
export interface PricingOption {
  'id' : string,
  'nameDe' : string,
  'nameEn' : string,
  'descriptionDe' : string,
  'descriptionEn' : string,
  'priceEur' : bigint,
  'membershipTier' : MembershipTier,
}
export interface Progress {
  'lessonId' : string,
  'lastAccessed' : Time,
  'completed' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type ThemePreference = { 'dark' : null } |
  { 'light' : null };
export interface TierFeature {
  'id' : string,
  'featureDe' : string,
  'featureEn' : string,
  'position' : bigint,
}
export interface TierFeatureList {
  'features' : Array<TierFeature>,
  'tier' : MembershipTier,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'theme' : ThemePreference,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'language' : LanguagePreference,
  'isSuspended' : boolean,
  'membership' : MembershipTier,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhyChooseSection {
  'descriptionDe' : string,
  'descriptionEn' : string,
  'featureCards' : Array<FeatureCard>,
  'titleDe' : string,
  'titleEn' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addFeedbackResponse' : ActorMethod<[FeedbackResponse], undefined>,
  'addFileReference' : ActorMethod<[FileReference], undefined>,
  'addLearningPath' : ActorMethod<[LearningPath], undefined>,
  'addLesson' : ActorMethod<[Lesson], undefined>,
  'addLevel' : ActorMethod<[Level], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteLearningPath' : ActorMethod<[string], undefined>,
  'deleteLesson' : ActorMethod<[string], undefined>,
  'deleteLevel' : ActorMethod<[string], undefined>,
  'downloadPdfFile' : ActorMethod<[string], HttpResponse>,
  'exportData' : ActorMethod<[], ExportData>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerFeedbackSubmissions' : ActorMethod<[], Array<FeedbackSubmission>>,
  'getCallerLanguagePreference' : ActorMethod<[], LanguagePreference>,
  'getCallerProgress' : ActorMethod<[], [] | [Array<Progress>]>,
  'getCallerThemePreference' : ActorMethod<[], ThemePreference>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getFeedbackResponses' : ActorMethod<[], Array<FeedbackResponse>>,
  'getFeedbackResponsesForSubmission' : ActorMethod<
    [string],
    Array<FeedbackResponse>
  >,
  'getFeedbackSubmissions' : ActorMethod<[], Array<FeedbackSubmission>>,
  'getFileReferences' : ActorMethod<[], Array<FileReference>>,
  'getHomepageContent' : ActorMethod<[], [] | [HomepageContent]>,
  'getLearningPaths' : ActorMethod<[], Array<LearningPath>>,
  'getLessonById' : ActorMethod<[string], [] | [Lesson]>,
  'getLessonCompletionStatus' : ActorMethod<[Principal, string], boolean>,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getLessonsByCategory' : ActorMethod<[string], Array<Lesson>>,
  'getLessonsByLevel' : ActorMethod<[string], Array<Lesson>>,
  'getLessonsByTag' : ActorMethod<[string], Array<Lesson>>,
  'getLevels' : ActorMethod<[], Array<Level>>,
  'getRecommendedLessons' : ActorMethod<[string, Principal], Array<Lesson>>,
  'getStripeConfiguration' : ActorMethod<[], [] | [StripeConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importData' : ActorMethod<[ExportData], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'reactivateUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'servePdfFile' : ActorMethod<[string], HttpResponse>,
  'setCallerLanguagePreference' : ActorMethod<[LanguagePreference], undefined>,
  'setCallerThemePreference' : ActorMethod<[ThemePreference], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitFeedback' : ActorMethod<[FeedbackSubmission], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerProgress' : ActorMethod<[Array<Progress>], undefined>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateHomepageContent' : ActorMethod<[HomepageContent], undefined>,
  'updateLearningPath' : ActorMethod<[LearningPath], undefined>,
  'updateLesson' : ActorMethod<[Lesson], undefined>,
  'updateLevel' : ActorMethod<[Level], undefined>,
  'updateTierFeatures' : ActorMethod<[Array<TierFeatureList>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];